'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class welcome
    
    '''<summary>
    '''frmWelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmWelcome As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ltlFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlFirstName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltlVowelCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlVowelCount As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltlYearsOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlYearsOld As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltlDaysUntil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlDaysUntil As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltlRunUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlRunUp As Global.System.Web.UI.WebControls.Literal
End Class
